/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JumpLink: typeof import('./src/components/JumpLink.vue')['default']
    LayoutBackGround: typeof import('./src/components/LayoutBackGround.vue')['default']
    LeftTitle: typeof import('./src/components/LeftTitle.vue')['default']
    RightTitle: typeof import('./src/components/RightTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
